server:
  port: 8080

spring:
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB

minio:
  endpoint: 10.70.151.109
  port: 9000
  accessKey: minio
  secretKey: minio
  secure: false
  bucketName: "gym"
  configDir: